[tox]
envlist = docs
skip_missing_interpreters = true

[testenv:docs]
description = Build the Sphinx documentation
extras = docs
commands = python -m sphinx -b html {toxinidir}/docs {toxinidir}/docs/_build/html {posargs}

[testenv:docs-clean]
description = Remove built/generated documentation artifacts
skip_install = true
deps =
allowlist_externals = rm
commands =
    rm -rf {toxinidir}/docs/_build {toxinidir}/docs/api/generated
